--CREATE DATABASE DEPARTMENT
--USE DEPARTMENT
--CREATE TABLE EMPLOYEE(
--Id int primary key identity,
--FULLNAME NVARCHAR (50) NOT NULL,
--AGE INT NOT NULL,CHECK(AGE>=0),
--EMAIL NVARCHAR  (255) UNIQUE NOT NULL,
--SALARY FLOAT CHECK (SALARY<2000 AND SALARY>300),
--)
--SELECT * FROM EMPLOYEE
--INSERT INTO EMPLOYEE
--VALUES('NAZ MZADEH',19,'AB@MAIL.COM',1500);
--INSERT INTO EMPLOYEE
--VALUES('aB CD',29,'D4@MAIL.COM',1580);
--SELECT *FROM EMPLOYEE
--UPDATE EMPLOYEE SET SALARY=1000 WHERE ID=1;
--SELECT SALARY FROM EMPLOYEE
--SELECT SALARY FROM EMPLOYEE WHERE SALARY BETWEEN 500 AND 1500
--SELECT FULLNAME,EMAIL,SALARY FROM EMPLOYEE ORDER BY SALARY DESC
--CREATE DATABASE UNI
--USE UNI
--CREATE TABLE STUDENTS(
--Id INT PRIMARY KEY IDENTITY,
--NAME NVARCHAR (50) NOT NULL,
--SURNAME NVARCHAR (60) DEFAULT NULL,
--PHONE NVARCHAR (255 ) UNIQUE,
--SCORE INT DEFAULT 50,
--COMMENT NVARCHAR (100) DEFAULT NULL,
--IsGRADUATED BIT  DEFAULT 0
--)
--INSERT INTO STUDENTS
--VALUES('NAZ' ,'MZADEH','068497484',100,'HELLO',0);
--INSERT INTO STUDENTS
--VALUES('ABC' ,'BCD','0684841484',90,'HI',1);
--INSERT INTO STUDENTS
--VALUES('DJDJ' ,'SJ','023284367',40,'BYE',1);
--DROP TABLE STUDENT
--UPDATE STUDENTS
--SET COMMENT= 'CONGRATULATIONS'
--WHERE SCORE>(SELECT AVG(SCORE) FROM STUDENTS)
--UPDATE STUDENTS
--SET COMMENT= 'SO BAD'
--WHERE SCORE<(SELECT AVG(SCORE) FROM STUDENTS)
--SELECT * FROM STUDENTS
--USE UNI
--CREATE TABLE GRADUATEDSTUDENT(
--Id INT PRIMARY KEY IDENTITY,
--ISGRADUATED BIT  DEFAULT 0

--)
--INSERT INTO GRADUATEDSTUDENT(ISGRADUATED)
--SELECT IsGRADUATED FROM STUDENTS WHERE IsGRADUATED=1
--SELECT * FROM GRADUATEDSTUDENT
--INSERT INTO GRADUATEDSTUDENT(ISGRADUATED)
--DELETE  FROM STUDENTS WHERE IsGRADUATED=1
--SELECT * FROM STUDENTS

CREATE DATABASE DB
USE DB
CREATE TABLE EMPLOYEEE(
ID  INT IDENTITY,
MKOD NVARCHAR (50),
SAAD NVARCHAR (255),
EMPLOYEEID INT FOREIGN KEY (EMPLOYEEID) REFERENCES EMPLOYEEE(ID),

)

CREATE TABLE EMPLOYEEID(
ID  INT PRIMARY KEY IDENTITY,



)

USE DB
CREATE TABLE PROFESSIONNN(
PROFID INT FOREIGN KEY (PROFID) REFERENCES PROFESSIONNN(ID),
VEZIFE NVARCHAR (50)
)


CREATE TABLE FILIAL(
ID  INT PRIMARY KEY IDENTITY,
FILIAL NVARCHAR (50)
)

CREATE TABLE PRODUCT(
ID  INT PRIMARY KEY IDENTITY,
NAME NVARCHAR (50),
ALISHQIYMET FLOAT,
SATISHQIYMET FLOAT
)


CREATE TABLE SALE(
ID  INT PRIMARY KEY IDENTITY,
PRODUCTID INT,
EMPLOYEEID INT,
DISCOUNT FLOAT,
DATE NVARCHAR,     --UNFINISHED
)

